version: '3.8'  # use 3.8 for better support and consistency

services:
  allcoaching_go:
    container_name: allcoaching_admin
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"  # expose internally only (not to host)
    ports:
      - "8000:80"
    environment:
      - VIRTUAL_HOST=api.allcoaching.in
      - VIRTUAL_PORT=80  # optional, only if app runs on different port internally
      - LETSENCRYPT_HOST=api.allcoaching.in
      - LETSENCRYPT_EMAIL=asmitkumarr082@gmail.com
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
