version: '3'

services:
  allcoaching_go:
    container_name: allcoaching_admin
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - "8000"  # expose to the internal proxy only (not ports)
    environment:
      - VIRTUAL_HOST=api.allcoaching.in
      - LETSENCRYPT_HOST=api.allcoaching.in
      - LETSENCRYPT_EMAIL=asmitkumarr082@gmail.com
    networks:
      - nginx-proxy