version: '3.8'  # use 3.8 for better support and consistency

services:
  allcoaching_go:
    container_name: allcoaching_admin
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"  # expose internally only (not to host)
    environment:
      - VIRTUAL_HOST=api.allcoaching.in
      - LETSENCRYPT_HOST=api.allcoaching.in
      - LETSENCRYPT_EMAIL=asmitkumarr082@gmail.com
    networks:
      - nginx_network

networks:
  nginx_network: