version: '3'
services:
  allcoaching_go:
    container_name: allcoaching_admin
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    environment:
      VIRTUAL_HOST: api.allcoaching.in
      LETSENCRYPT_HOST: api.allcoaching.in
      LETSENCRYPT_EMAIL: asmitkumarr082@gmail.com