version: '3.8'  # use 3.8 for better support and consistency

services:
  allcoaching_go:
    container_name: allcoaching_admin
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - VIRTUAL_HOST=155.248.254.181


