# Generated by Django 4.2.3 on 2025-01-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('user_id', models.PositiveBigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'auth_token',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'banner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('institute_id', models.BigIntegerField()),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('banner_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('director_name', models.CharField(max_length=150)),
                ('user_id', models.PositiveBigIntegerField(unique=True)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'institute',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InstituteBanners',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('institute_id', models.BigIntegerField()),
                ('banner_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'institute_banners',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.PositiveBigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('date_joined', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('is_active', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('is_institute', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TestRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
