# Generated by Django 4.2.3 on 2024-04-12 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
       
        migrations.RenameField(
            model_name='livestreamlogs',
            old_name='uuid',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='livestreamlogs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 59, 46, 352102, tzinfo=datetime.timezone.utc)),
        )
       
    ]
