# Generated by Django 4.2.3 on 2023-07-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='adminblogs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='adminconfig',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='admintestseriescategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='admintestseriessubcategorycontent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='admintestsubcategories',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='coursebanners',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='coursedocument',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='coursegolive',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='coursetimetableitem',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='coursetimetablesubject',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='coursevideo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='coursevideocomments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='documentplaylist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='feedcategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='feedcomments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='feedimages',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='feedpolloptions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='feedreport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hibernatesequence',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='insleads',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='insreview',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='inssubscription',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='instestseries',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='instestseriesplaylist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='instestseriesquestions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='instestseriesuserquestionresponses',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='instestseriesuserresponsebrief',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mainbanners',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='payouts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='questionreport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='studenthistory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='studentmessage',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='studentmessageimages',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='studentpinlist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='testseriesquestionresponse',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='testseriesresponse',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='videoplaylist',
            options={'managed': True},
        ),
    ]
