# Generated by Django 4.2.3 on 2025-01-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrel',
            name='banners',
            field=models.ManyToManyField(to='app.banner'),
        ),
    ]
