# Generated by Django 4.2.3 on 2023-11-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('coupon', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('max_usage', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'coupon',
                'managed': True,
            },
        ),
    ]
