# Generated by Django 4.2.3 on 2025-01-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrel',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
