# Generated by Django 4.2.3 on 2024-04-04 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_institute_account_id_institute_account_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('rtmps_key', models.CharField(max_length=255)),
                ('rtmps_url', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.institute')),
            ],
            options={
                'db_table': 'live_stream',
                'managed': True,
            },
        ),
    ]
