# Generated by Django 4.2.3 on 2024-04-10 14:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_livestream'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStreamLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 4, 10, 14, 49, 42, 957023, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='encoded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='length',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestream',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app.course'),
            preserve_default=False,
        ),
    ]
