# Generated by Django 4.2.3 on 2025-01-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_testrel_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrel',
            name='photos',
        ),
    ]
